const express = require('express')
const BlockController = require('../controllers/BlockController')
const FrontController = require('../controllers/FrontController')
const AdminController = require('../controllers/admin/AdminController')
const BlogController = require('../controllers/admin/BlogController')
const CategoryController = require('../controllers/admin/CategoryController')
const CurdController = require('../controllers/CurdController')
const ContactController = require('../controllers/admin/ContactController')
const UserController = require('../controllers/user/UserController')
const {CheckUserAuth, AuthRole} = require('../middleware/auth')
const router = express.Router()  
const image_middleware = require('../middleware/image_middleware')


router.get('/',BlockController.home)   
router.get('/about',BlockController.about)    
router.get('/contact',BlockController.contact) 
router.get('/login',BlockController.login)    
router.get('/blog',BlockController.blog) 
router.get('/detail/:id',BlockController.detail)
router.get('/detail/display',BlockController.DisplayCategory) 

router.get('/admin/dashboard',CheckUserAuth,AdminController.dashboard)
router.get('/admin/nishant/dashboard',CheckUserAuth,AuthRole('admin'),AdminController.admindashboard)
router.get('/admin/createuser',CheckUserAuth,AuthRole('admin'),BlogController.createbloguser)
router.get('/admin/createblog',CheckUserAuth,BlogController.createblog)
router.post('/bloginsertuser',image_middleware,BlogController.bloginsertuser)
router.post('/bloginsert',image_middleware,BlogController.bloginsert)
router.get('/admin/displayuser',CheckUserAuth,BlogController.displayuser)
router.get('/admin/displayblog',CheckUserAuth,BlogController.displayblog)
router.get('/admin/viewuser/:id',CheckUserAuth,BlogController.viewuser)
router.get('/admin/viewblog/:id',CheckUserAuth,BlogController.viewblog)
router.get('/admin/edituser/:id',CheckUserAuth,BlogController.edituser)
router.get('/admin/editblog/:id',CheckUserAuth,BlogController.editblog)
router.post('/admin/blogupdateuser/:id',CheckUserAuth,image_middleware,BlogController.Updatebloguser)
router.post('/admin/blogupdate/:id',CheckUserAuth,image_middleware,BlogController.Updateblog)
router.get('/admin/deleteblog/:id',CheckUserAuth,BlogController.deleteblog)

router.get('/admin/createcategoryuser',CheckUserAuth,CategoryController.createcategoryuser)
router.get('/admin/createcategory',CheckUserAuth,CategoryController.createcategory)
router.get('/admin/categoryuser',CheckUserAuth,CategoryController.categoryuser)
router.get('/admin/categorydisplay',CheckUserAuth,CategoryController.categorydisplay)
router.post('/admin/categoryinsertuser',CheckUserAuth,CategoryController.categoryinsertuser)
router.post('/admin/categoryinsert',CheckUserAuth,CategoryController.categoryinsert)
router.get('/admin/viewcategoryuser/:id',CheckUserAuth,CategoryController.viewcategoryuser)
router.get('/admin/viewcategory/:id',CheckUserAuth,CategoryController.viewcategory)
router.get('/admin/editcategoryuser/:id',CheckUserAuth,CategoryController.editcategoryuser)
router.get('/admin/editcategory/:id',CheckUserAuth,CategoryController.editcategory)
router.post('/admin/categoryupdateuser/:id',CheckUserAuth,CategoryController.categoryupdateuser)
router.post('/admin/categoryupdate/:id',CheckUserAuth,CategoryController.categoryupdate)
router.get('/admin/deletecategory/:id',CheckUserAuth,CategoryController.deletecategory)

router.post('/admin/contactinsert',CheckUserAuth,ContactController.contactinsert)
router.get('/admin/contactdisplay',CheckUserAuth,ContactController.contactdisplay)
router.get('/admin/viewcontact/:id',CheckUserAuth,ContactController.viewcontact)
router.get('/admin/editcontact/:id',CheckUserAuth,ContactController.editcontact)
router.post('/admin/contactupdate/:id',CheckUserAuth,ContactController.contactupdate)
router.get('/admin/deletecontact/:id',CheckUserAuth,ContactController.deletecontact)

router.get('/curd/create',CheckUserAuth,CurdController.Createform)
router.post('/curd/insert',CheckUserAuth,CurdController.InsertData)
router.get('/curd/display',CheckUserAuth,CurdController.displaydata)
router.get('/curd/view/:id',CheckUserAuth,CurdController.curdview)
router.get('/curd/edit/:id',CheckUserAuth,CurdController.editcurd)
router.post('/curd/update/:id',CheckUserAuth,CurdController.updatecurd)
router.get('/curd/delete/:id',CheckUserAuth,CurdController.deletecurd)

router.get('/register',UserController.register)
router.post('/registerinsert',UserController.registerinsert)
router.post('/verifylogin',UserController.verifylogin)
router.get('/logout',UserController.logout)

module.exports = router;