const express = require('express')
const BlockController = require('../controllers/BlockController')
const FrontController = require('../controllers/FrontController')
const AdminController = require('../controllers/admin/AdminController')
const BlogController = require('../controllers/admin/BlogController')
const CategoryController = require('../controllers/admin/CategoryController')
const CurdController = require('../controllers/CurdController')
const ContactController = require('../controllers/admin/ContactController')
const UserController = require('../controllers/user/UserController')
const auth = require('../middleware/auth')
const router = express.Router()  
const image_middleware = require('../middleware/image_middleware')


router.get('/',BlockController.home)   
router.get('/about',BlockController.about)    
router.get('/contact',BlockController.contact) 
router.get('/login',BlockController.login)    
router.get('/blog',BlockController.blog) 
router.get('/detail/:id',auth,BlockController.detail)
router.get('/detail/display',auth,BlockController.DisplayCategory) 


router.get('/admin/dashboard',auth,AdminController.dashboard)
router.get('/admin/createblog',auth,BlogController.createblog)
router.post('/bloginsert',image_middleware,BlogController.bloginsert)
router.get('/admin/displayblog',auth,BlogController.displayblog)
router.get('/admin/viewblog/:id',auth,BlogController.viewblog)
router.get('/admin/editblog/:id',auth,BlogController.editblog)
router.post('/admin/blogupdate/:id',auth,image_middleware,BlogController.Updateblog)
router.get('/admin/deleteblog/:id',auth,BlogController.deleteblog)

router.get('/admin/createcategory',auth,CategoryController.createcategory)
router.get('/admin/categorydisplay',auth,CategoryController.categorydisplay)
router.post('/admin/categoryinsert',CategoryController.categoryinsert)
router.get('/admin/viewcategory/:id',auth,CategoryController.viewcategory)
router.get('/admin/editcategory/:id',auth,CategoryController.editcategory)
router.post('/admin/categoryupdate/:id',auth,CategoryController.categoryupdate)
router.get('/admin/deletecategory/:id',auth,CategoryController.deletecategory)

router.post('/admin/contactinsert',auth,ContactController.contactinsert)
router.get('/admin/contactdisplay',auth,ContactController.contactdisplay)
router.get('/admin/viewcontact/:id',auth,ContactController.viewcontact)
router.get('/admin/editcontact/:id',auth,ContactController.editcontact)
router.post('/admin/contactupdate/:id',auth,ContactController.contactupdate)
router.get('/admin/deletecontact/:id',auth,ContactController.deletecontact)

router.get('/curd/create',auth,CurdController.Createform)
router.post('/curd/insert',auth,CurdController.InsertData)
router.get('/curd/display',auth,CurdController.displaydata)
router.get('/curd/view/:id',auth,CurdController.curdview)
router.get('/curd/edit/:id',auth,CurdController.editcurd)
router.post('/curd/update/:id',auth,CurdController.updatecurd)
router.get('/curd/delete/:id',auth,CurdController.deletecurd)

router.get('/register',UserController.register)
router.post('/registerinsert',UserController.registerinsert)
router.post('/verifylogin',UserController.verifylogin)
router.get('/logout',UserController.logout)

module.exports = router;